language: python
python:
    - "3.4"

install:
    - pip install -r requirements.txt
    - nvm install node
    - nvm use node
    - npm install

script:
    - nvm use node
    - npm run test
    - npm run build
    - python manage.py collectstatic --noinput
    - python manage.py test --verbosity=2
    - codeclimate-test-reporter
