# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_create_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('transation_type', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('transfer', 'transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals_from', to='accounts.Account')),
                ('account_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposits_to', to='accounts.Account')),
            ],
        ),
    ]
