# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20160829_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(db_index=True),
        ),
    ]
