# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20160829_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='_amount',
        ),
    ]
