# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='creator',
        ),
    ]
