# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_create_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
