# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 02:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20160829_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
